"""
Assisted design actions for VibeCAD.

This module provides deterministic, preview-only suggested fixes that:
- Are generated by Python code (never by LLM)
- Require explicit user approval before application
- Are reversible via KiCad undo
- Are logged for review

The LLM is only used to explain proposed changes, not to generate them.
"""

from .base import (
    Suggestion,
    SuggestionStatus,
    SuggestionGenerator,
    SuggestionApplier,
    ActionResult,
    ActionLog,
    ActionLogger,
    GeometryChange,
)
from .board_outline_generator import BoardOutlineGenerator, BoundingBox
from .component_position_generator import ComponentPositionGenerator
from .unrouted_nets_highlighter import UnroutedNetsHighlighter
from .preview_renderer import PreviewRenderer, PreviewOverlay, PreviewManager
from .suggestion_manager import SuggestionManager

__all__ = [
    # Base classes
    'Suggestion',
    'SuggestionStatus',
    'SuggestionGenerator',
    'SuggestionApplier',
    'ActionResult',
    'ActionLog',
    'ActionLogger',
    'GeometryChange',
    # Generators
    'BoardOutlineGenerator',
    'BoundingBox',
    'ComponentPositionGenerator',
    'UnroutedNetsHighlighter',
    # Preview
    'PreviewRenderer',
    'PreviewOverlay',
    'PreviewManager',
    # Manager
    'SuggestionManager',
]
